### ISSUE TITLE
preload requests

### ISSUE THREAD

**Issue by aripiprazole** [gabrielleeg1/ticoteco#177]
```
Warning: usePreloadedQuery(): usePreloadedQuery was passed a preloaded query that was created with a different environment than the one that is currently in context. In the future, this will become a hard error. 
    at CurrentPosts (webpack-internal:///./src/timeline/Timeline.tsx:38:26)
    at Suspense
    at div
    at eval (webpack-internal:///../../node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at Timeline (webpack-internal:///./src/timeline/Timeline.tsx:77:155)
    at main
    at eval (webpack-internal:///../../node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at div
    at eval (webpack-internal:///../../node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at Layout (webpack-internal:///./src/layout/Layout.tsx:29:26)
    at TimelinePage
    at AuthProvider (webpack-internal:///./src/auth/AuthProvider.tsx:41:26)
    at RelayEnvironmentProvider (webpack-internal:///../../node_modules/react-relay/lib/relay-hooks/RelayEnvironmentProvider.js:21:24)
    at EnvironmentProvider (webpack-internal:///../../node_modules/@chakra-ui/react-env/dist/chakra-ui-react-env.esm.js:120:24)
    at ColorModeProvider (webpack-internal:///../../node_modules/@chakra-ui/color-mode/dist/chakra-ui-color-mode.esm.js:190:21)
    at ThemeProvider (webpack-internal:///../../node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:96:64)
    at ThemeProvider (webpack-internal:///../../node_modules/@chakra-ui/system/dist/chakra-ui-system.esm.js:70:27)
    at ChakraProvider (webpack-internal:///../../node_modules/@chakra-ui/provider/dist/chakra-ui-provider.esm.js:22:24)
    at ChakraProvider (webpack-internal:///../../node_modules/@chakra-ui/react/dist/chakra-ui-react.esm.js:253:23)
    at App (webpack-internal:///./src/pages/_app.tsx:58:27)
    at O (webpack-internal:///../../node_modules/next-firebase-auth/build/index.browser.js:2:15756)
    at LoadableImpl (webpack-internal:///../../node_modules/next/dist/shared/lib/loadable.js:67:9)
    at ErrorBoundary (webpack-internal:///../../node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:20740)
    at ReactDevOverlay (webpack-internal:///../../node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:23199)
    at Container (webpack-internal:///../../node_modules/next/dist/client/index.js:149:9)
    at AppContainer (webpack-internal:///../../node_modules/next/dist/client/index.js:651:26)
    at Root (webpack-internal:///../../node_modules/next/dist/client/index.js:773:27)
```

**Comment by aripiprazole** [comment]
I think it is easier to request manually to the API
